# Generated by Django 4.0.5 on 2022-06-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('interests', models.CharField(max_length=150)),
                ('color', models.CharField(max_length=30)),
                ('food', models.CharField(max_length=30)),
                ('hobby', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
